server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: service-fegin
    client:
      path: /client/**
      serviceId: demo-1
  #host:
  #  connect-timeout-millis: 10000
  # socket-timeout-millis: 60000

#hystrix:
#  command:
#    default:
#      execution:
#      isolation:
#         thread:
#           timeoutInMilliseconds: 60000

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000


