server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

spring:
  application:
    name: demo-1
  cloud:
    config:
      label: master
      profile: local
      uri: http://localhost:8888



